### ISSUE TITLE
 return the menu settings Time Lapse

### ISSUE THREAD

**Issue by gonzo070** [alex-agency/XYC#11]
Hi! Huge request to return the menu settings Time Lapse. Let me explain why: many use the camera on quadrocopters, for that would shoot photos in a Time Lapse I put between shutter 12 seconds, it is not possible to set a standard application. Thanks in advance.

**Comment by alex-agency** [comment]
Hi, I'd love to add it. But, unfortunately, it won't work in the latest 1.2.13 firmware. They did something with reboot function and now it works unstable. Also I can't use
"t app key shutter" more than one time in the loop for example, because camera freezes after first shot. I have 23L version of camera.
It was the main reason why I removed Time Lapse script from XYC. Also HDR function in the XYC doesn't work too.

**Comment by gonzo070** [comment]
Strangely, my camera with firmware 1.2.13 (Z23L). Installed on the camera your old version  tweak, where there is a menu with Timelaps. Everything is working.

**Comment by alex-agency** [comment]
Really strange, Let me check it. Which date of XYC old version tweak has?
You can see it in the head of script: 
-  Xiaomi Yi Configurator  \* 
-  12/01/2015  0.3.4 Alex  \* 

If it works I'll be able to fix latest script.
Thank you.

**Comment by gonzo070** [comment]
10/23/2015 0.3.3

**Comment by gonzo070** [comment]
I would be very happy if you functional Timelapse reattached.

**Comment by alex-agency** [comment]
Sure, I'll return the Timelapse part for you even if it won't work with my camera. )

**Comment by gonzo070** [comment]
Спасибо :-)

**Comment by whothisbeme** [comment]
Thank you for returning the Timelapse part - I too am having issues with the Yi App's built in timelapse function. I recieve a few 13MB~ RAWs and the rest are unusable 31MB~ RAWs.. :+1: :+1: :+1:

I have noticed this issue is not present when using the RAWLAPSE v2 nutsey script to loop capture photos.
- Z22 Model 
- 1.2.13 firmware 
- XYC (ad36d33)

**Comment by alex-agency** [comment]
Hey guys! 
I've added Time-lapse script. )

Actually, I've added three different time-lapse scripts:
1. Time-lapse Custom: allows to set amount of time-lapse cycles (from 1 to 360), interval between them (from 1 to 3600 secs), allows to run only one time (script won't enable after second boot), allows power off camera after script complete.
2. Time-lapse Infinity: allows to use countless time-lapse cycles, but you're able to set interval between cycles only.
3. Time-lapse HDR: same as Infinity, but instead of one shoot it takes preconfigured HDR shoots (from 3 to 6).
Also all of these time-lapse scripts you can use with any photo settings like RAW, ISO and so on.

I hope it helps you.
Alex

**Comment by gonzo070** [comment]
Great news!!!!!!! Cool! Let's test! Thank you so much!

**Comment by gonzo070** [comment]
everything works fine! Thank you!
