### ISSUE TITLE
1600x1200 problem

### ISSUE THREAD

**Issue by marcoperty** [alex-agency/XYC#21]
Hi, today I've done some try with the 0.3.3 release and 1600x1200 video mode. I noticed that with 60fps and 35mbps of bitrate my xiaomi (z23l with the latest firmware) cuts videos after few seconds and only the first video has 35mbps of bitrate while the others have smaller bitrate. My micro sd is a 32gb samsung evo class 10 uhs1. I couldn't understand the reason of the issue so I did a last try setting up 30fps instead of 60 and I noticed that also with a bitrate of 45mbps the cam doesn't cut the videos. Can you say why the cam doesn't support 1600x1200 60fps? Thank you and sorry for my english

**Comment by alex-agency** [comment]
Hi, 

Its better to use 0.3.4 or latest script from master which has Superview feature. 

Sometimes I also have similar behaviour but with different resolutions. It happens because camera can't write some amount of data to SD card. 
The reason of this behaviour could be different. 
I saw it when processor of camera is loaded by some another operations like WIFI, Telnet and so on. Also the amount of light (daylight, room light, at night) is important. Of course SD-card it self should be fast. 
Several times I saw issue with SD-card after connecting camera to computer through USB cable. In this case you need reformat your SD-card by one of camera official app for iOS or Android. 

I've just tested latest script for you with 1600x1200 video mode with 60 fps and 35 mb bitrate with different lights. I also have z23l camera and my SD-card is 32gb Sandisk Ultra silver.
The camera recorded 2 minutes of daylight with defined settings and when I went back to house with room light it has created a new file with different 21 mb bitrate, but the same 1600x1200 and 60 fps. And it wasn't changed even when I went back to daylight again. 

Hope it will help you. )

Best Regards,
Alex

**Comment by marcoperty** [comment]
Ok thank u very much, you've been very kind and clear!
