### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by PariahPhoenix** [alex-agency/XYC#5]
I only know a small amount of coding but when I try to run XYC 0.3.2 through Telnet on my Xiaomi I get a Syntax Error code for line 4 but I see nothing on the code itself why it would do that. Maybe you would have a clue.

**Comment by alex-agency** [comment]
Its happen because you have Windows line ending. You need Unix line ending for run script in Linux.
Try to change line ending via Notepad++ or Sublime Text editors.
If you download file without changes you won't have any line ending issues.

**Comment by PariahPhoenix** [comment]
I haven't done any changes on it. I download it straight to the micro SD card and run a telnet client on my android phone and I receive the error.

**Comment by alex-agency** [comment]
No doubt Windows line separators are the root cause. If you have Syntax error which referred to empty line of script it is wrong EOL (end-of-line) characters. You can see it via Notepad++ (Select View > Show Symbol > Show All Characters from the Menu bar). Windows/MS-DOS uses CR+LF to indicate end-of-lines. And UNIX uses LF character to indicate line termination (EOL character).
I've just verified script again it has LF character which means Unix line ending.
Try one more time for download this script it should works fine.
